In [3]:
import numpy as np

x = np.array([[10, 30,20], [20, 60,20]])
print("Original array:")
print(x)
print("Mean of each column:")
print(x.mean(axis=0))
print("Mean of each row:")
print(x.mean(axis=1))

Original array:
[[10 30 20]
 [20 60 20]]
Mean of each column:
[15. 45. 20.]
Mean of each row:
[20.         33.33333333]
