In [19]:
 import numpy as np
 
    
ab = np.array([[0,1,2],[3,4,5],[6,7,8]])
print("original array is :\n", (ab))
print("sum of the diagonal is :\n",np.trace(ab))


original array is :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
sum of the diagonal is :
 12
